---
title: "Wrapup"
output: html_notebook
---

## Wrapup

To forecast energy (electricity) trends and energy (electricity) prices, we use four different neural network models to forecast electricity prices. 
We use Python to implement Convolutional Neural Networks (CNN), Time Distributed Feed-Forward Neural Networks, Long Short-term Memory Recurrent Neural Networks (LSTM), and Stacked LSTM, while also improving these models to improve accuracy.

We then use Root Mean Squared Error to evaluate the accuracy of the models, which is important for judging the neural network architecture for time series forecasting.


## Conclusions

Rank the model with Root Mean Squared Error:

╒══════════════════════════════════════════════════╤════════╕
│ Model                                            │   RMSE │
╞══════════════════════════════════════════════════╪════════╡
│ LSTM                                             │  2.157 │
├──────────────────────────────────────────────────┼────────┤
│ Bidirectional LSTMs                              │  2.339 │
├──────────────────────────────────────────────────┼────────┤
│ CNN                                              │  4.212 │
├──────────────────────────────────────────────────┼────────┤
│ Stacked CNN                                      │  6.063 │
├──────────────────────────────────────────────────┼────────┤
│ Time-distributed Mulitlayer Perceptron           │  2.717 │
├──────────────────────────────────────────────────┼────────┤
│ Optimised Time-distributed Mulitlayer Perceptron │  2.559 │
├──────────────────────────────────────────────────┼────────┤
│ stacked LSTM                                     │  3.332 │
╘══════════════════════════════════════════════════╧════════
Therefore, we can say the LSTM model was the 'best'.
